#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
nohup $OPENSHIFT_REPO_DIR/tomcat/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/tomcat > $OPENSHIFT_HOMEDIR/tomcat-7.0/logs/server.log 2>&1 &
